name: Sync to GitLab
on: [push]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to GitLab
        run: |
          git remote add gitlab git@gitlab.kuleuven.be:u0148621/myown.git
          git push --force gitlab "refs/remotes/origin/*:refs/heads/*"
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
